-- MySQL Script generated by MySQL Workbench
-- Tue Jan 24 10:25:13 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema painelde_voos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema painelde_voos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `painelde_voos` DEFAULT CHARACTER SET latin1 ;
USE `painelde_voos` ;

-- -----------------------------------------------------
-- Table `painelde_voos`.`fabricantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `painelde_voos`.`fabricantes` (
  `COD_FABRICANTE` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `FABRICANTE` VARCHAR(55) NOT NULL COMMENT '',
  `SITE` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`COD_FABRICANTE`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `painelde_voos`.`aeronaves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `painelde_voos`.`aeronaves` (
  `DSC_EQUIPAMENTO` VARCHAR(55) NOT NULL COMMENT '',
  `COD_FABRICANTE` INT(11) NOT NULL COMMENT '',
  `MODELO` VARCHAR(40) NOT NULL COMMENT '',
  `DESCRICAO` TEXT NOT NULL COMMENT '',
  `NUM_PASSAGEIROS` INT(3) NOT NULL COMMENT '',
  UNIQUE INDEX `DSC_EQUIPAMENTO` (`DSC_EQUIPAMENTO` ASC)  COMMENT '',
  INDEX `COD_FABRICANTE` (`COD_FABRICANTE` ASC)  COMMENT '',
  INDEX `DSC_EQUIPAMENTO_2` (`DSC_EQUIPAMENTO` ASC)  COMMENT '',
  CONSTRAINT `fk_cod_fabricante`
    FOREIGN KEY (`COD_FABRICANTE`)
    REFERENCES `painelde_voos`.`fabricantes` (`COD_FABRICANTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `painelde_voos`.`aeroportos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `painelde_voos`.`aeroportos` (
  `cod_aeroporto` INT(6) NOT NULL AUTO_INCREMENT COMMENT '',
  `cod_iata` VARCHAR(6) NOT NULL COMMENT '',
  `cod_icao` VARCHAR(6) NOT NULL COMMENT '',
  `loc` VARCHAR(50) NOT NULL COMMENT '',
  `nom_aeroporto` VARCHAR(100) NOT NULL COMMENT '',
  `nom_cidade` VARCHAR(100) NOT NULL COMMENT '',
  `possui_siv` VARCHAR(1) NOT NULL COMMENT '',
  `sig_uf` VARCHAR(2) NOT NULL COMMENT '',
  `vnom_curto` VARCHAR(100) NOT NULL COMMENT '',
  `weather` VARCHAR(100) NOT NULL COMMENT '',
  `datahora_offline` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`cod_aeroporto`)  COMMENT '',
  INDEX `cod_iata` (`cod_iata` ASC)  COMMENT '',
  INDEX `cod_icao` (`cod_icao` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 56
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `painelde_voos`.`cias_aereas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `painelde_voos`.`cias_aereas` (
  `NOM_CIA` VARCHAR(10) NOT NULL COMMENT '',
  `SIG_CIA_AEREA` VARCHAR(3) NOT NULL COMMENT '',
  `NOME` VARCHAR(55) NOT NULL COMMENT '',
  `DESCRICAO` TEXT NOT NULL COMMENT '',
  `SITE` VARCHAR(250) NOT NULL COMMENT '',
  UNIQUE INDEX `NOM_CIA` (`NOM_CIA` ASC)  COMMENT '',
  INDEX `NOM_CIA_2` (`NOM_CIA` ASC)  COMMENT '',
  INDEX `SIG_CIA_AEREA` (`SIG_CIA_AEREA` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `painelde_voos`.`voos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `painelde_voos`.`voos` (
  `NUM_VOO` VARCHAR(8) NOT NULL COMMENT '',
  `DAT_VOO` VARCHAR(6) NOT NULL COMMENT '',
  `DAT_VOO_DT` DATE NOT NULL COMMENT '',
  `HOR_PREV` VARCHAR(5) NOT NULL COMMENT '',
  `HOR_PREV_DT` DATETIME NOT NULL COMMENT '',
  `HOR_CONF` VARCHAR(5) NOT NULL COMMENT '',
  `HOR_CONF_DT` DATETIME NOT NULL COMMENT '',
  `NUM_TPS` VARCHAR(4) NOT NULL COMMENT '',
  `NUM_GATE` VARCHAR(4) NOT NULL COMMENT '',
  `TXT_OBS` VARCHAR(45) NOT NULL COMMENT '',
  `NOM_CIA` VARCHAR(55) NOT NULL COMMENT '',
  `SIG_CIA_AEREA` VARCHAR(3) NOT NULL COMMENT '',
  `DSC_EQUIPAMENTO` VARCHAR(60) NOT NULL COMMENT '',
  `NOM_AEROPORTO` VARCHAR(55) NOT NULL COMMENT '',
  `COD_IATA` VARCHAR(5) NOT NULL COMMENT '',
  `COD_ICAO` VARCHAR(5) NOT NULL COMMENT '',
  `NOM_LOCALIDADE` VARCHAR(55) NOT NULL COMMENT '',
  `SIG_UF` VARCHAR(4) NOT NULL COMMENT '',
  `NOM_PAIS` VARCHAR(45) NOT NULL COMMENT '',
  `DSC_NATUREZA` ENUM('Doméstico','Internacional') NOT NULL COMMENT '',
  `DSC_SENTIDO` ENUM('Partida','Chegada') NOT NULL COMMENT '',
  `DSC_STATUS` VARCHAR(55) NOT NULL COMMENT '',
  `ULT_ATUALIZACAO` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`NUM_VOO`)  COMMENT '',
  INDEX `DSC_EQUIPAMENTO` (`DSC_EQUIPAMENTO` ASC)  COMMENT '',
  INDEX `NUM_VOO` (`NUM_VOO` ASC)  COMMENT '',
  INDEX `DAT_VOO` (`DAT_VOO` ASC)  COMMENT '',
  INDEX `COD_IATA` (`COD_IATA` ASC)  COMMENT '',
  INDEX `COD_ICAO` (`COD_ICAO` ASC)  COMMENT '',
  INDEX `DAT_VOO_DT` (`DAT_VOO_DT` ASC)  COMMENT '',
  INDEX `SIG_CIA_AEREA` (`SIG_CIA_AEREA` ASC)  COMMENT '',
  CONSTRAINT `fk_cod_iata`
    FOREIGN KEY (`COD_IATA`)
    REFERENCES `painelde_voos`.`aeroportos` (`cod_iata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cod_icao`
    FOREIGN KEY (`COD_ICAO`)
    REFERENCES `painelde_voos`.`aeroportos` (`cod_icao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dsc_equipamento`
    FOREIGN KEY (`DSC_EQUIPAMENTO`)
    REFERENCES `painelde_voos`.`aeronaves` (`DSC_EQUIPAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sig_cia_aerea`
    FOREIGN KEY (`SIG_CIA_AEREA`)
    REFERENCES `painelde_voos`.`cias_aereas` (`SIG_CIA_AEREA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `painelde_voos`.`voos_escalas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `painelde_voos`.`voos_escalas` (
  `NUM_VOO` VARCHAR(10) NOT NULL COMMENT '',
  `DAT_VOO_DT` DATE NOT NULL COMMENT '',
  `COD_ESCALA` VARCHAR(3) NOT NULL COMMENT '',
  `DSC_ESCALA` VARCHAR(45) NOT NULL COMMENT '',
  INDEX `NUM_VOO` (`NUM_VOO` ASC, `DAT_VOO_DT` ASC)  COMMENT '',
  INDEX `DAT_VOO_DT` (`DAT_VOO_DT` ASC)  COMMENT '',
  CONSTRAINT `fk_dat_voo_dt`
    FOREIGN KEY (`DAT_VOO_DT`)
    REFERENCES `painelde_voos`.`voos` (`DAT_VOO_DT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_num_voo`
    FOREIGN KEY (`NUM_VOO`)
    REFERENCES `painelde_voos`.`voos` (`NUM_VOO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
